// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA23-94okVKPtzEBegcEqB9CVzo5dUdLzU',
    appId: '1:239507357893:web:90af7fc1f5e9d42f76b0ac',
    messagingSenderId: '239507357893',
    projectId: 'fir-f3d3d',
    authDomain: 'fir-f3d3d.firebaseapp.com',
    databaseURL: 'https://fir-f3d3d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f3d3d.appspot.com',
    measurementId: 'G-3GN3N4CK4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKmUwVshqDFrlY0KK5jApBog0uM-mpdqc',
    appId: '1:239507357893:android:0431e7c3883e64ed76b0ac',
    messagingSenderId: '239507357893',
    projectId: 'fir-f3d3d',
    databaseURL: 'https://fir-f3d3d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f3d3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK7706hAAEBXzjfS7ql4JVd3pzUAW0NUs',
    appId: '1:239507357893:ios:f6fd834207979e6176b0ac',
    messagingSenderId: '239507357893',
    projectId: 'fir-f3d3d',
    databaseURL: 'https://fir-f3d3d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f3d3d.appspot.com',
    iosBundleId: 'com.example.soleilenquete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK7706hAAEBXzjfS7ql4JVd3pzUAW0NUs',
    appId: '1:239507357893:ios:f6fd834207979e6176b0ac',
    messagingSenderId: '239507357893',
    projectId: 'fir-f3d3d',
    databaseURL: 'https://fir-f3d3d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f3d3d.appspot.com',
    iosBundleId: 'com.example.soleilenquete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA78orkjPf7lSsWohZy2BfzzRNbvi0qpVA',
    appId: '1:239507357893:web:0cbbcdf6de2a7e1576b0ac',
    messagingSenderId: '239507357893',
    projectId: 'fir-f3d3d',
    authDomain: 'fir-f3d3d.firebaseapp.com',
    databaseURL: 'https://fir-f3d3d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f3d3d.appspot.com',
    measurementId: 'G-XJG7LTT4JE',
  );

}